/* eslint-disable quotes */
export const PADOVA_UNIVERSITY = 'Università degli Studi di Padova';
export const universities = [
  'Accademia di Belle Arti di BARI',
  'Accademia di Belle Arti di URBINO',
  'Accademia di Belle Arti di PERUGIA "Pietro Vannucci"',
  'Accademia di Belle Arti di VITERBO "Lorenzo da Viterbo"',
  'Istituto superiore industrie artistiche ISIA di URBINO',
  'Conservatorio di musica di AVELLINO "Domenico Cimarosa"',
  'Conservatorio di musica di BARI "Niccolò Piccinni"',
  'Conservatorio di musica di BENEVENTO "Nicola Sala"',
  'Conservatorio di musica di CAMPOBASSO "Lorenzo Perosi"',
  'Conservatorio di musica di COSENZA "Stanislao Giacomantonio"',
  'Conservatorio di musica di L\'AQUILA "Alfredo Casella"',
  'Conservatorio di musica di MANTOVA "Lucio Campiani"',
  'Conservatorio di musica di MATERA "Egidio R. Duni"',
  'Conservatorio di musica di MONOPOLI "Nino Rota"',
  'Conservatorio di musica di PERUGIA "Francesco Morlacchi"',
  'Conservatorio di musica di PESARO "Gioacchino Rossini"',
  'Conservatorio di musica di PIACENZA "Giuseppe Nicolini"',
  'Conservatorio di musica di POTENZA "Gesualdo da Venosa"',
  'Conservatorio di musica di SALERNO "G. Martucci"',
  'Istituto statale superiore di studi musicali e coreutici "Gaetano Braga" di TERAMO',
  'Conservatorio di musica di TRIESTE "Giuseppe Tartini"',
  'Conservatorio di musica di UDINE "Jacopo Tomadini"',
  'Conservatorio di musica di VENEZIA "Benedetto Marcello" - palazzo pisani',
  'Conservatorio di musica di VERONA "E. F. dall\'Abaco"',
  'Conservatorio di musica di VIBO VALENTIA "Fausto Torrefranca"',
  'Conservatorio di musica di VICENZA "Arrigo Pedrollo"',
  'Liuc-Università Cattaneo',
  'Università degli Studi Link Campus University',
  'Università San Raffaele',
  'Università degli Studi Internazionali di Roma',
  'Università Lum De Gennaro',
  "Università della Valle d'Aosta",
  'Università di Enna Kore',
  'Università Campus Biomedico di Roma',
  'Università Cattolica del Sacro Cuore',
  'Università Vita-Salute San Raffaele',
  'Saint Camillus International University of Health Sciences',
  'Humanitas University',
  'Università Campus Bio-Medico',
  'Alta Scuola in media, comunicazione e spettacolo ALMED',
  'Alta Scuola impresa e società ALTIS ',
  "Alta Scuola per l'ambiente ASA",
  'Alta Scuola di psicologia Agostino Gemelli ASAG',
  'Alta Scuola di economia e relazioni internazionali ASERI',
  'Alta Scuola in economia agro-alimentare SMEA',
  'Libera Università Internazionale degli Studi Sociali "Guido Carli"',
  'Libera Università Maria Santissima Assunta',
  'SSML Gregorio VII',
  'Università degli Studi Internazionali di Roma',
  'Libera Università Mediterranea Jean Monnet',
  'Università Carlo Cattaneo LIUC',
  'Istituto Universitario Salesiano di Venezia IUSVE',
  'Università telematica e-Campus',
  'Università telematica "Guglielmo Marconi"',
  'Università degli Studi "Niccolò Cusano"',
  'Università telematica internazionale "UniNettuno"',
  'Università telematica "Pegaso"',
  'Università telematica San Raffaele',
  'Università telematica UNITELMA Sapienza',
  'Università telematica Universitas Mercatorum',
  'Università telematica "Leonardo da Vinci"',
  'Università telematica Giustino Fortunato',
  'Università telematica "Italian University Line"',
  'SID Scuola Italiana Design',
  'IED Istituto Europeo di design Milano',
  'IED Istituto Europeo di design Roma',
  'IED Istituto Europeo di design Torino',
  'IED Istituto Europeo di design Venezia',
  'IED Istituto Europeo di design Firenze',
  'IED Istituto Europeo di design Cagliari',
  'IED Istituto Europeo di design Como',
  'Istituto Marangoni Firenze',
  'Istituto Marangoni Fashion School Milano',
  'Istituto Marangoni Milano design School',
  "Università della Valle d'Aosta",
  'Libera università di Bolzano',
  'Università degli Studi di Enna "Kore"',
  'Università degli Studi di Scienze Gastronomiche Bra, Colorno',
  'Libera Università Mediterranea Giuseppe Degennaro',
  'Università Carlo Cattaneo LIUC',
  'Libera università di lingue e comunicazione IULM- Milano',
  'Università Cattolica del Sacro Cuore - Milano',
  'Università Cattolica del Sacro Cuore - Brescia',
  'Università Cattolica del Sacro Cuore - Cremona',
  'Università Cattolica del Sacro Cuore - Piacenza',
  'Università Cattolica del Sacro Cuore - Roma',
  'Università commerciale Luigi Bocconi - Milano',
  'Università Vita-Salute San Raffaele - Milano',
  'Humanitas University',
  'Università degli Studi "Suor Orsola Benincasa"',
  'Università per stranieri "Dante Alighieri" di Reggio Calabria',
  'Libera università internazionale degli studi sociali Guido Carli - Roma',
  'Libera Università Maria Santissima Assunta',
  'Università Campus Bio-Medico - Roma',
  'Università degli Studi Internazionali di Roma',
  'Università degli Studi Link Campus University - Roma',
  'Università Europea di Roma',
  'Saint Camillus International University of Health Sciences - Roma',
  'ESCP Business School- Torino',
  'International University College of Turin',
  "Istituto d'Arte Applicata e Design IAAD - Torino",
  'Istituto Universitario Salesiano di Venezia IUSVE',
  'Università telematica Giustino Fortunato - Benevento',
  'Università telematica "Italian University Line" - Firenze',
  'Università telematica "Pegaso" - Napoli',
  'Università telematica e-Campus',
  'Università telematica "Guglielmo Marconi"',
  'Università degli Studi "Niccolò Cusano"',
  'Università telematica internazionale "UniNettuno"',
  'Università telematica San Raffaele',
  'Università telematica UNITELMA Sapienza',
  'Università telematica Universitas Mercatorum',
  'Università telematica "Leonardo da Vinci"',
  'Università degli Studi "Gabriele D\'Annunzio"',
  'Università degli Studi di L"Aquila',
  'Università degli Studi di Teramo',
  'Accademia di Belle Arti di L"AQUILA',
  'Scuola Universitaria Superiore “Gran Sasso Science Institute" (GSSI)',
  'Università degli Studi della Basilicata',
  'Università degli Studi "Magna Graecia" di Catanzaro',
  'Università degli Studi Mediterranea di Reggio Calabria',
  'Università della Calabria',
  'Accademia di Belle Arti di CATANZARO',
  'Accademia di Belle Arti di REGGIO CALABRIA',
  'Conservatorio di musica di REGGIO CALABRIA "Francesco Cilea"',
  'Istituto Universitario "Suor Orsola Benincasa"',
  'Seconda Università degli Studi di Napoli',
  'Università degli Studi del Sannio',
  'Università degli Studi di Napoli "Federico II"',
  'Università degli Studi di Napoli "L\'Orientale"',
  'Università degli Studi di Napoli "Partenophe"',
  'Università degli Studi di Salerno',
  'Accademia di Belle Arti di NAPOLI',
  'Conservatorio di musica di NAPOLI "S. Pietro a Majella"',
  'Università degli Studi di Bologna',
  'Università degli Studi di Ferrara',
  'Università degli Studi di Modena e Reggio Emilia',
  'Università degli Studi di Parma',
  'Accademia di Belle Arti di BOLOGNA',
  'Accademia di Belle Arti legalmente riconosciuta di RAVENNA',
  'Istituto superiore industrie artistiche ISIA di FAENZA',
  'Conservatorio di musica di BOLOGNA "Giovan B. Martini"',
  'Conservatorio di musica di CESENA "Bruno Maderna"',
  'Conservatorio di musica di FERRARA "Girolamo Frescobaldi"',
  'Conservatorio di musica di PARMA "Arrigo Boito"',
  'SISSA - Scuola Internazionale Superiore di Studi Avanzati',
  'Università degli Studi di Trieste',
  'Università degli Studi di Udine',
  'IUSM - Università degli Studi di Roma "Foro Italico"',
  'Libera Università degli Studi "San Pio V',
  'LUISS - Libera Università Internazionale degli Studi Sociali Guido Carli',
  'LUMSA - Libera Università "Maria Ss. Assunta"',
  'Università "Campus Bio-Medico"di Roma',
  'Università degli Studi della Tuscia',
  'Università degli Studi di Cassino',
  'Università degli Studi di Roma "La Sapienza"',
  'Università degli Studi di Roma "Tor Vergata"',
  'Università degli Studi Europea di Roma',
  'Università degli Studi "Roma Tre"',
  'Accademia di Belle Arti di FROSINONE',
  'Accademia di Belle Arti di ROMA',
  'Accademia di Belle Arti "Rome University of Fine Arts"',
  'Istituto superiore industrie artistiche ISIA di ROMA',
  'Accademia nazionale di arte drammatica di ROMA "Silvio d\'Amico"',
  'Accademia nazionale di danza di ROMA',
  'Conservatorio di musica di FROSINONE "Licinio Refice"',
  'Conservatorio di musica di LATINA "Ottorino Respighi"',
  'Conservatorio di musica di ROMA "Santa Cecilia"',
  'Università Europea di Roma',
  'Università degli Studi di Genova',
  'Accademia di Belle Arti "Accademia Ligustica"',
  'Accademia di Belle Arti "Isadora Duncan"',
  'Conservatorio di musica di GENOVA "Nicolò Paganini"',
  'Conservatorio di musica di LA SPEZIA "Giacomo Puccini"',
  'IULM - Libera Università di Lingue e ComunicazionePolitecnico di MilanoUniversità Carlo Cattaneo',
  'LIUCUniversità Cattolica del Sacro Cuore',
  'Università Commerciale Luigi Bocconi',
  "Università degli Studi dell'Insubria Varese-Como",
  'Università degli Studi di Bergamo',
  'Università degli Studi di Brescia',
  'Università degli Studi di Milano',
  'Università degli Studi di Milano-Bicocca',
  'Università degli Studi di Pavia',
  'Università Vita-Salute San Raffaele',
  'Accademia di Belle Arti di MILANO "Brera"',
  'Accademia di Belle Arti di BERGAMO "Carrara"',
  'Accademia di Belle Arti di BRESCIA "LABA" - libera accademia di belle arti',
  'Accademia di Belle Arti di BRESCIA "Santagiulia"',
  'Accademia di Belle Arti di COMO "Aldo Galli"',
  'Accademia di Belle Arti di MILANO "ACME"',
  'Accademia di Belle Arti di MILANO "NABA" - nuova accademia di belle arti',
  'Conservatorio di musica di BRESCIA "Luca Marenzio"',
  'Conservatorio di musica di COMO "Giuseppe Verdi"',
  'Conservatorio di musica di MILANO "Giuseppe Verdi"',
  'Università Politecnica delle Marche',
  'Università degli Studi di Camerino',
  'Università degli Studi di Macerata',
  'Università degli Studi di Urbino Carlo Bo',
  'Accademia di Belle Arti di MACERATA',
  'Istituto superiore industrie artistiche ISIA di PESCARA',
  'Conservatorio di musica di FERMO "Giovambattista Pergolesi"',
  'Conservatorio di musica di PESCARA "Luisa d\'Annunzio"',
  'Università degli Studi del Molise',
  'Politecnico di Torino',
  'Università degli Studi del Piemonte Orientale "Amedeo Avogadro"',
  'Università degli Studi di Torino',
  'Università di Scienze Gastronomiche',
  'Accademia di Belle Arti di TORINO "Albertina"',
  'Accademia di Belle Arti di CUNEO',
  'Accademia di Belle Arti di NOVARA "ACME"',
  'Conservatorio di musica di ALESSANDRIA "Antonio Vivaldi"',
  'Conservatorio di musica di CUNEO "G.F. Ghedini"',
  'Conservatorio di musica di NOVARA "Guido Cantelli"',
  'Conservatorio di musica di TORINO "Giuseppe Verdi"',
  "Istituto d'Arte Applicata e Design IAAD",
  'ESCP Europe',
  'International University College of Turin',
  'Università degli Studi di Scienze Gastronomiche',
  'LUM - Libera Università Mediterranea "Jean Monnet"',
  'Politecnico di Bari',
  'Università degli Studi di Bari',
  'Università degli Studi di Foggia',
  'Università degli Studi del Salento',
  'Accademia di Belle Arti di FOGGIA',
  'Accademia di Belle Arti di LECCE',
  'Conservatorio di musica di FOGGIA "Umberto Giordano"',
  'Conservatorio di musica di LECCE "Tito Schipa"',
  'Università degli Studi di CagliariUniversità degli Studi di Sassari',
  'Accademia di Belle Arti di SASSARI',
  'Conservatorio di musica di CAGLIARI "Pierluigi da Palestrina"',
  'Conservatorio di musica di SASSARI "Luigi Canepa"',
  'Università degli Studi di Catania',
  'Università degli Studi di Messina',
  'Università degli Studi di Palermo',
  'Accademia di Belle Arti di CATANIA',
  'Accademia di Belle Arti di PALERMO',
  'Accademia di Belle Arti "Abadir"',
  'Accademia di Belle Arti di SIRACUSA "Rosario Gagliardi"',
  'Conservatorio di musica di MESSINA "Arcangelo Corelli"',
  'Conservatorio di musica di PALERMO "A. Scarlatti"',
  'Conservatorio di musica di TRAPANI "Antonio Scontrino"',
  'Scuola Normale Superiore Pisa',
  'Scuola Superiore di Studi Universitari e di Perfezionamento "Sant\'Anna" Pisa',
  'Università degli Studi di Firenze',
  'Università degli Studi di Pisa',
  'Università degli Studi di Siena',
  'Università per Stranieri di Siena',
  'Accademia di Belle Arti di CARRARA',
  'Accademia di Belle Arti di FIRENZE',
  'Istituto superiore industrie artistiche ISIA di FIRENZE',
  'Conservatorio di musica di FIRENZE "Luigi Cherubini"',
  'Libera Università di Bolzano',
  'Università degli Studi di Trento',
  'Conservatorio di musica di BOLZANO "Claudio Monteverdi"',
  'Conservatorio di musica di TRENTO "Francesco A. Bonporti"',
  'Università degli Studi di Perugia',
  'Università per Stranieri di Perugia',
  "Università della Valle d'Aosta - Université de la Vallée D'Aoste",
  'Università Iuav di VeneziaUniversità "Ca\' Foscari" di Venezia',
  PADOVA_UNIVERSITY,
  'Università degli Studi di Verona',
  'Accademia di Belle Arti di VENEZIA',
  'Accademia di Belle Arti di VERONA',
  'Conservatorio di musica di ADRIA "Antonio Buzzolla"',
  'Conservatorio di musica di CASTELFRANCO VENETO "Agostino Steffani"',
  'Conservatorio di musica di PADOVA "Cesare Pollini"',
  'Conservatorio di musica di ROVIGO "Francesco Venezze"',
];
